### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by dmuntean** [monsterxx03/gospy#1]
Hi,

This project is a great idea!

However, I couldn't get it installed - I tried running

`go get github.com/monsterxx03/gospy`

and got the following output:
> package gospy/pkg/proc: unrecognized import path "gospy/pkg/proc" (import path does not begin with hostname)
> package gospy/pkg/term: unrecognized import path "gospy/pkg/term" (import path does not begin with hostname)

I then tried installing with go modules enabled:
`GO111MODULE=on go get github.com/monsterxx03/gospy`

But still wasn't able to install it:
> go: finding github.com/monsterxx03/gospy latest
> go: github.com/monsterxx03/gospy@v0.0.0-20191007080200-56907f947b8c: parsing go.mod: 
 unexpected module path "gospy"
> go: error loading module requirements

Could you please update the readme with the installation instructions?

**Comment by monsterxx03** [comment]
Hi @dmuntean , I've updated REAMED:  https://github.com/monsterxx03/gospy#build-from-source

Please let me know if it don't work.

**Comment by monsterxx03** [comment]
Also, you can download pre built binary from release page: https://github.com/monsterxx03/gospy/releases

**Comment by dmuntean** [comment]
Great, thanks! I was able to build the project and successfully run it.

**Comment by no-serve-people** [comment]
2024/04/01 18:05:59 Failed to parse: map[internal/abi.Type:0xc0000263a0] from binary
